### ISSUE TITLE
WARNING: Get https://api.vtbs.moe/v1/short timeout

### ISSUE THREAD

**Issue by IsaacTheMouse** [benx1n/hoshinobot-plugin-ddcheck#2]
> [2022-05-25 09:43:14,090 nonebot] WARNING: Get https://api.vtbs.moe/v1/short timeout
[2022-05-25 09:43:16,181 nonebot] WARNING: Traceback (most recent call last):
  File "/home/ubuntu/Hoshino/hoshino/modules/hoshinobot-plugin-ddcheck/__init__.py", line 43, in ddcheck
    res = await get_reply(text)
  File "/home/ubuntu/Hoshino/hoshino/modules/hoshinobot-plugin-ddcheck/data_source.py", line 157, in get_reply
    vtb_list = await get_vtb_list()
  File "/home/ubuntu/Hoshino/hoshino/modules/hoshinobot-plugin-ddcheck/data_source.py", line 81, in get_vtb_list
    await update_vtb_list()
  File "/home/ubuntu/Hoshino/hoshino/modules/hoshinobot-plugin-ddcheck/data_source.py", line 46, in update_vtb_list
    uid_list = list(set((info["mid"] for info in vtb_list)))
  File "/home/ubuntu/Hoshino/hoshino/modules/hoshinobot-plugin-ddcheck/data_source.py", line 46, in <genexpr>
    uid_list = list(set((info["mid"] for info in vtb_list)))
KeyError: 'mid'

**Comment by YuanHaoReginald** [comment]
我遇到了别的报错错误，不过报错点跟你这个差不多

我的解决方案是在`datasource.py`的 49 行修改：

```
              vtb_list += result
              vtb_list = list(filter(lambda info: 'mid' in info, vtb_list))
              uid_list = list(set((info["mid"] for info in vtb_list)))
              vtb_list = list(filter(lambda info: info["mid"] in uid_list, vtb_list))
```

第二行是我修改的内容。

不太清楚原始意图是啥所以没发pr，作者看到修复一下吧

**Comment by benx1n** [comment]
修复了
请拉取最新代码重新尝试
