### ISSUE TITLE
用uid查成分可以成功查到，用昵称提示不存在

### ISSUE THREAD

**Issue by SanaChitose** [benx1n/hoshinobot-plugin-ddcheck#7]
今天新发现的
![图片](https://user-images.githubusercontent.com/102790983/184081088-8d7e8847-5aac-4dfe-9b3e-078e888ad6f8.png)
![图片](https://user-images.githubusercontent.com/102790983/184081119-1e221cd7-5f20-499c-9da9-e05074946c2f.png)

**Comment by SanaChitose** [comment]
报错如下
![图片](https://user-images.githubusercontent.com/102790983/184081260-12b8dcd6-52c6-484d-bb3d-e37f6c07966f.png)
[2022-08-11 15:03:22,080 ddcheck] INFO: Message 1374938107 triggered ddcheck.
[2022-08-11 15:03:22,205 nonebot] WARNING: Traceback (most recent call last):
  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\__init__.py", line 43, in ddcheck
    res = await get_reply(text)
  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\data_source.py", line 152, in get_reply
    uid = await get_uid_by_name(name)
  File "C:\bot\HoshinoBot\hoshino\modules\hoshinobot-plugin-ddcheck\data_source.py", line 92, in get_uid_by_name
    for user in result["data"]["result"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by benx1n** [comment]
无法复现
![image](https://user-images.githubusercontent.com/48101337/184880223-195f9c71-1e76-4d88-a827-e539d872580f.png)

**Comment by SanaChitose** [comment]
我这边也无法复现了，可能是网络抽风问题，先关了吧，打扰本心佬了

**Comment by SaltyCoIa** [comment]
遇到了相同的问题，输入昵称时报错相同，但我是输入uid也是报错
![S ZZSMMV6B`~}9%$)$LW A2](https://user-images.githubusercontent.com/75192177/198866498-0c134929-621c-42c3-bb65-364f13adec7c.png)

[2022-10-30 14:55:52,274 nonebot] INFO: Self: 1518685955, Message 1745403245 from 1502824494@[群:993633782]: '查成分 189
7834'
[2022-10-30 14:55:52,291 ddcheck] INFO: Message 1745403245 triggered ddcheck.
[2022-10-30 14:55:52,274] INFO in message: Self: 1518685955, Message 1745403245 from 1502824494@[群:993633782]: '查成分
1897834'
[2022-10-30 14:55:52,291] INFO in msghandler: Message 1745403245 triggered ddcheck.
[2022-10-30 14:55:52,885 nonebot] WARNING: Error in get_medals(1897834): 'data'
[2022-10-30 14:55:52,885] WARNING in data_source: Error in get_medals(1897834): 'data'
请问楼主解决了问题吗

**Comment by SanaChitose** [comment]
现在 几乎是100%复现了~本心佬有空再看看吗
![图片](https://user-images.githubusercontent.com/102790983/199864809-0f9c9e15-4109-4eb0-9780-b21953e134c2.png)

**Comment by dfmjndm** [comment]
请reopen该issue

**Comment by benx1n** [comment]
明天看一下= =

**Comment by benx1n** [comment]
@dfmjndm @SanaChitose 请更新后按readme重新配置cookie再次尝试

**Comment by SanaChitose** [comment]
> @dfmjndm @SanaChitose 请更新后按readme重新配置cookie再次尝试

获取了新的cookies后还是不行，难道真的是我网络太烂？
![图片](https://github.com/benx1n/hoshinobot-plugin-ddcheck/assets/102790983/15640545-f5d6-4863-8c2f-29455f076bb0)
![图片](https://github.com/benx1n/hoshinobot-plugin-ddcheck/assets/102790983/04a13b96-22fd-49a2-a1fe-5ccda3894f97)

**Comment by benx1n** [comment]
> > @dfmjndm @SanaChitose 请更新后按readme重新配置cookie再次尝试
> 
> 获取了新的cookies后还是不行，难道真的是我网络太烂？ ![图片](https://user-images.githubusercontent.com/102790983/245006693-15640545-f5d6-4863-8c2f-29455f076bb0.png) ![图片](https://user-images.githubusercontent.com/102790983/245006993-04a13b96-22fd-49a2-a1fe-5ccda3894f97.png)

看了一下原仓库的提交记录，添加了header中的agent，怀疑是B站加了这方面的限制，下午再看看

**Comment by benx1n** [comment]
@SanaChitose 修复了，再试一下 cfcaf7f

**Comment by SanaChitose** [comment]
> @SanaChitose 修复了，再试一下 [cfcaf7f](https://github.com/benx1n/hoshinobot-plugin-ddcheck/commit/cfcaf7fbb25e99d931aa505ddca9bce443bee1fe)

已验证修复，感谢本心佬！
